# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Residency',
            field=models.CharField(choices=[('Karakoram', 'Karakoram'), ('Nilgiri', 'Nilgiri'), ('Himadri', 'Himadri'), ('Jwalamukhi', 'Jwalamukhi'), ('Udaigiri', 'Udaigiri'), ('Individual', 'Individual Housing')], default='Karakoram', max_length=15),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='Vinay@iitd.ac.in', max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='vinay', max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='typeOfUser',
            field=models.CharField(choices=[('Student', 'Student'), ('Warden', 'Warden'), ('Faculty', 'Faculty')], default='Student', max_length=7),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='vinay', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='Vinay Rebeiro', max_length=40),
        ),
    ]
