# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0002_auto_20160331_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='roomNo',
            field=models.IntegerField(default=0),
        ),
    ]
