# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0004_auto_20160331_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='vinay', max_length=40),
        ),
    ]
