# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0005_auto_20160331_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='userName',
        ),
    ]
