# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0007_auto_20160331_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='resolvedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
