# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0008_auto_20160331_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_roomNo',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned to any authority personnel'), ('unresolved', 'Unresolved'), ('resolved', 'resolved')], default='unassigned', max_length=12),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('plumber', 'Plumber'), ('carpentry', 'Carpentry'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('library', 'Library'), ('csc', 'Computer Services Center'), ('mess', 'Mess'), ('security', 'Security'), ('others', 'Others')], default='others', max_length=15),
        ),
    ]
