# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0011_auto_20160403_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='origin',
            field=models.CharField(choices=[('Karakoram', 'Karakoram'), ('Nilgiri', 'Nilgiri'), ('Himadri', 'Himadri'), ('Jwalamukhi', 'Jwalamukhi'), ('Udaigiri', 'Udaigiri'), ('Institute', 'IIT Delhi'), ('Individual', 'Individual House')], default='Karakoram', max_length=20),
        ),
    ]
