# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintSystem', '0013_auto_20160407_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_text',
            new_name='comment_title',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 10, 9, 31, 38, 116413, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
